version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./combined.log:/app/combined.log  # Optional: Mount log file if needed for persistence
    restart: unless-stopped
